# Generated by Django 2.1.5 on 2019-02-20 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.SmallIntegerField(choices=[(1, 'Primer'), (2, 'Segon'), (3, 'Tercer'), (4, 'Quart'), (5, 'Cinquè')])),
                ('degree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Degree')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField()),
                ('amount', models.IntegerField()),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.Comment')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Subject')),
            ],
            bases=('polls.comment',),
        ),
        migrations.CreateModel(
            name='TeacherComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.Comment')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Teacher')),
            ],
            bases=('polls.comment',),
        ),
        migrations.AddField(
            model_name='qualification',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Teacher'),
        ),
    ]
