# Generated by Django 2.1.5 on 2019-02-20 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190220_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
