# Generated by Django 2.1.5 on 2019-02-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190220_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Contains the description of the web')),
                ('display', models.BooleanField(default=False, help_text='Only the first marked will be displayed')),
            ],
        ),
    ]
